export const ENTITY_ICON_SLUGS = [
	'across',
	'alchemy-pay',
	'aldrin',
	'allbridge',
	'amber-group',
	'anchorage',
	'ascendex',
	'auros',
	'axelar',
	'axiom',
	'b2c2',
	'backpack-exchange',
	'banana-gun',
	'banxa',
	'bb-router',
	'bigone',
	'binance',
	'bingx',
	'bit2me',
	'bitfinex',
	'bitflyer',
	'bitget',
	'bitgo',
	'bithumb',
	'bitmart',
	'bitrue',
	'bitso',
	'bitstamp',
	'bitunix',
	'bitvavo',
	'blofin',
	'bloom',
	'bridge-xyz',
	'btc-turk',
	'bybit',
	'caladan',
	'celer',
	'chainlink-ccip',
	'changelly',
	'changenow',
	'chorus-one',
	'circle',
	'circle-cctp',
	'cobo',
	'coinbase',
	'coincheck',
	'coindcx',
	'coinex',
	'coins-ph',
	'coinspot',
	'coinspro',
	'coinsquare',
	'coinw',
	'copper',
	'crema',
	'cropper',
	'crypto-com',
	'cumberland',
	'cykura',
	'debridge',
	'deepcoin',
	'direct',
	'dflow',
	'digifinex',
	'drift',
	'falconx',
	'figment',
	'fireblocks',
	'flowdesk',
	'fluxbeam',
	'fomo',
	'fordefi',
	'foxbit',
	'galaxy-digital',
	'gate',
	'generic-bot',
	'gemini',
	'gmgn',
	'goosefx',
	'gsr',
	'htx',
	'hyperlane',
	'independent-reserve',
	'jito',
	'jump-crypto',
	'jupiter',
	'kamino',
	'keyrock',
	'kraken',
	'kucoin',
	'latoken',
	'layerzero',
	'lbank',
	'lifi',
	'lifinity',
	'maestro',
	'mango-markets',
	'marginfi',
	'marinade',
	'mayan',
	'mercado-bitcoin',
	'mercuryo',
	'meson',
	'meteora',
	'mexc',
	'mintc',
	'moonpay',
	'mudrex',
	'ndax',
	'neon-evm',
	'okx',
	'onramper',
	'open-dex',
	'openbook',
	'orbiter',
	'orca',
	'padre',
	'paribu',
	'paxos',
	'paypal',
	'phemex',
	'phoenix',
	'photon',
	'pionex',
	'poloniex',
	'portal',
	'probit',
	'pumpfun',
	'pumpswap',
	'ramp-network',
	'rango',
	'raydium',
	'relay',
	'revolut',
	'robinhood',
	'router-protocol',
	'saber',
	'sanctum',
	'sardine',
	'saros',
	'serum',
	'simplex',
	'solayer',
	'solana-mev-bot',
	'squid',
	'stargate',
	'step-finance',
	'stripe',
	'symbiosis',
	'synapse',
	'tether',
	'titan',
	'tokocrypto',
	'toobit',
	'transak',
	'trojan',
	'troy',
	'unlimit',
	'upbit',
	'wazirx',
	'weex',
	'whitebit',
	'wintermute',
	'wormhole',
	'xt-com',
	'zebpay',
	'zerohash',
	'zeta-markets',
	'zeus-network'
] as const;

export type EntityIconSlug = (typeof ENTITY_ICON_SLUGS)[number];

type EntityIcon = { slug: EntityIconSlug; url: string };

const knownSlugs = new Set<string>(ENTITY_ICON_SLUGS);
const VECTOR_ENTITY_ICON_SLUGS = new Set<EntityIconSlug>([
	'fomo',
	'direct',
	'generic-bot',
	'open-dex',
	'padre',
	'solana-mev-bot'
]);
export const EXECUTION_PROGRAM_ICON_SLUGS: Readonly<Record<string, EntityIconSlug>> = {
	AgmLJBMDCqWynYnQiPCuj9ewsNNsBJXyzoUhD9LJzN51: 'fomo',
	DRAkNQsJrWKx8VLCMFcpAfNiYtsX4e7pVpjz1vgcsya3: 'open-dex',
	AxiomxSitiyXyPjKgJ9XSrdhsydtZsskZTEDam3PxKcC: 'axiom',
	AxiomfHaWDemCFBLBayqnEnNwE6b7B2Qz3UmzMpgbMG6: 'axiom',
	BLUR9cL8HqZzu5bSaC7VRX25RCG93Hv3T6NPyKxQhWUT: 'axiom',
	FLASHX8DrLbgeR8FcfNV1F5krxYcYMUdBkrP1EPBtxB9: 'axiom',
	DGMgNKpqygARV2pHZfW4kNQSHT9F3Ly2BKWqvpYrAg5C: 'gmgn',
	gmgnpkxVcSYnREsFamJygtcqo5QLbZCYNSJJVP7e2XW: 'gmgn',
	GMgnVFR8Jb39LoXsEVzb3DvBy3ywCmdmJquHUy1Lrkqb: 'gmgn',
	'9yMwSPk9mrXSN7yDHUuZurAh1sjbJsfpUqjZ7SvVtdco': 'trojan',
	troyXT7Ty3s2rjJe4bqWaroUrS4Fjd8rbHHNHxcACF4: 'trojan',
	term9YPb9mzAsABaqN71A4xdbxHmpBNZavpBiQKZzN3: 'padre',
	BSfD6SHZigAfDWSjzD5Q41jw8LmKwtmjskPH9XW1mrRW: 'photon',
	BANANAjs7FJiPQqJTGFzkZJndT9o7UmKiYYGaJz6frGu: 'banana-gun',
	MaestroAAe9ge5HTc64VbBQZ6fP77pwvrhM8i1XWSAx: 'maestro',
	b1oomGGqPKGD6errbyfbVMBuzSC8WtAAYo8MwNafWW1: 'bloom',
	troY36YiPGqMyAYCNbEqYCdN2tb91Zf7bHcQt7KUi61: 'troy',
	BBRouter1cVunVXvkcqeKkZQcBK7ruan37PPm3xzWaXD: 'bb-router',
	minTcHYRLVPubRK8nt6sqe2ZpWrGDLQoNLipDJCGocY: 'mintc',
	JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4: 'jupiter',
	jupoNjAxXgZ4rjzxzPMP4oxduvQsQtZzyknqvzYNrNu: 'jupiter',
	DCA265Vj8a9CEuX1eb1LWRnDT7uK6q1xMipnNyatn23M: 'jupiter',
	MAyhSmzXzV1pTf7LsNkrNwkWKTo4ougAJ1PPg47MD4e: 'pumpfun',
	MEViEnscUm6tsQRoGd9h6nLQaQspKj7DB2M5FwM3Xvz: 'solana-mev-bot',
	B3111yJCeHBcA1bizdJjUFPALfhAfSRnAbJzGUtnt56A: 'binance',
	proVF4pMXVaYqmy4NjniPh4pqKNfMmsihgd4wdkCX3u: 'okx',
	'6m2CDdhRgxpH4WjvdzxAYbGxwdGUz5MziiL5jek2kBma': 'okx',
	DF1ow4tspfHX9JwWJsAb9epbkA8hmpSEAtxXy1V27QBH: 'dflow',
	T1TANpTeScyeqVzzgNViGDNrkQ6qHz9KrSBS4aNXvGT: 'titan',
	s7SunwrPG5SbViEKiViaDThPRJxkkTrNx2iRPN3exNC: 'bitget',
	'6Vo3245eszAb5wuqEMw8mGdbfRUdKbHhDHP5LcaGuTAB': 'generic-bot',
	execQYVfDRoioKs242MQmKVa9FkTm4EEcHkbvt4hdKt: 'generic-bot',
	'3s1rAymURnacreXreMy718GfqW6kygQsLNka1xDyW8pC': 'generic-bot',
	BoobsBSMpFRBA91sNwKLYShRRQPH5GjoCH4NhLUt4yRo: 'generic-bot',
	AKbotMAGJmYPwV8z55Lqiqgijt2KcjLeFGue5sw1noHM: 'generic-bot',
	'7obtMdiXQaLCao2mCRzsanxRusUH8QAz8eT5PJyUTHFQ': 'generic-bot',
	m9obQHAPyZeZ88w7XUY8Te6a8rBmhXsfKco7u8G8tnB: 'generic-bot',
	'3CSRQSomjeEdimgg2jZxWLaq53drtzVnu25PTBpL2rhi': 'generic-bot',
	AveaiuA1emN71q9mS2QQ9BEWNAAHmp8sHSvwLFHQjufM: 'generic-bot',
	'6BRbqfVvpywTFK1bLH2p44GQy15tYBepubu1vvV7DrE6': 'generic-bot',
	NinafKYvKDCH26v6uEpfDjyuDjjpbdfhiPjrJV6FTFs: 'generic-bot',
	E52MR3wWQJG7mdBxLbw5tLcpF7DNzBWFKfacQ1HFSVrv: 'generic-bot',
	FAdo9NCw1ssek6Z6yeWzWjhLVsr8uiCwcWNUnKgzTnHe: 'generic-bot',
	sattCHvHkM4XHLyadnU4KQtuNWZbWVDKzuPhmJBXCkq: 'generic-bot',
	DDsnwb7dxKSjzTYDFjU8F6rpYNZa1sp7Fmfb2nGDAMEo: 'generic-bot',
	AN225ksocfZpbPVEbwffiANbtUdYbySM3WJ6dbsYAqij: 'generic-bot',
	G7MVcM9YzGxrmLtmobUgyt8A6WhQ2dgQX3aSJcPejdEp: 'generic-bot'
};

const aliases: Record<string, EntityIconSlug> = {
	'axiombot': 'axiom',
	'axiombot1': 'axiom',
	'axiombot2': 'axiom',
	'backpack': 'backpack-exchange',
	'bananagun': 'banana-gun',
	'bananagunbot': 'banana-gun',
	'bbrouter': 'bb-router',
	'bonkbot': 'bb-router',
	'btcturk': 'btc-turk',
	'circlecctp': 'circle-cctp',
	'coinsph': 'coins-ph',
	'cryptocom': 'crypto-com',
	'dexcelerate': 'open-dex',
	'generic': 'generic-bot',
	'genericbot': 'generic-bot',
	'driftv2': 'drift',
	'gateio': 'gate',
	'huobi': 'htx',
	'huobiglobal': 'htx',
	'jupiteraggregator': 'jupiter',
	'jupiterdca': 'jupiter',
	'jupiterlo': 'jupiter',
	'jupiterperpskeeper': 'jupiter',
	'lifinityswapv2': 'lifinity',
	'maestrobot': 'maestro',
	'mango': 'mango-markets',
	'mintech': 'mintc',
	'mintchy': 'mintc',
	'openbookv2': 'openbook',
	'opendex': 'open-dex',
	'padregg': 'padre',
	'pumpmayhem': 'pumpfun',
	'pheonix': 'phoenix',
	'photonnbot': 'photon',
	'routerprotocolbridge': 'router-protocol',
	'solanamevbot': 'solana-mev-bot',
	'tokocrypto': 'tokocrypto',
	'trojanbot': 'trojan',
	'troybot': 'troy',
	'xtcom': 'xt-com',
	'zerohash': 'zerohash',
	'zeta': 'zeta-markets'
};
const removableSuffixes = new Set([
	'1',
	'2',
	'bot',
	'bridge',
	'crypto',
	'custody',
	'dex',
	'exchange',
	'global',
	'hot',
	'liquidity',
	'protocol',
	'router',
	'service',
	'treasury',
	'v1',
	'v2',
	'wallet'
]);
const matchRules = [...ENTITY_ICON_SLUGS]
	.map((slug) => [slug.replaceAll('-', ''), slug] as const)
	.sort((left, right) => right[0].length - left[0].length);

function normalize(value: string): string {
	return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function resolveCandidate(candidate: string): EntityIconSlug | null {
	if (aliases[candidate]) return aliases[candidate];
	if (knownSlugs.has(candidate)) return candidate as EntityIconSlug;
	const compact = candidate.replaceAll('-', '');
	if (aliases[compact]) return aliases[compact];
	if (knownSlugs.has(compact)) return compact as EntityIconSlug;
	return null;
}

export function getEntityIcon(label?: string | null): { slug: EntityIconSlug; url: string } | null {
	const normalized = normalize(label || '');
	if (!normalized) return null;
	let resolved = resolveCandidate(normalized);
	const parts = normalized.split('-');
	while (!resolved && parts.length > 1 && removableSuffixes.has(parts.at(-1) || '')) {
		parts.pop();
		resolved = resolveCandidate(parts.join('-'));
	}
	if (!resolved) {
		const compact = normalized.replaceAll('-', '');
		resolved = matchRules.find(([needle]) => compact.includes(needle))?.[1] ?? null;
	}
	if (!resolved) return null;
	return entityIcon(resolved);
}

export function getExecutionProgramIcon(programId?: string | null): EntityIcon | null {
	const slug = EXECUTION_PROGRAM_ICON_SLUGS[programId || ''];
	return slug ? entityIcon(slug) : null;
}

function entityIcon(slug: EntityIconSlug): EntityIcon {
	return {
		slug,
		url: `/entity-icons/${slug}.${VECTOR_ENTITY_ICON_SLUGS.has(slug) ? 'svg' : 'webp'}`
	};
}
